version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=rgbjoy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=web-rgbjoy-2022
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: