[phases]

# Install dependencies
[phases.install]
run = "pnpm install"

# Pre-build phase: Clean up any leftover files or cache
[phases.pre-build]
run = "rm -rf .next/cache"

# Build the Next.js app
[phases.build]
run = "pnpm migrate_build"

# Start the application
[phases.start]
run = "pnpm start"
