import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "users_sessions" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "media" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "posts" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "_posts_v" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "redirects" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "redirects_rels" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "payload_kv" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "payload_locked_documents" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "payload_locked_documents_rels" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "payload_preferences" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "payload_preferences_rels" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "payload_migrations" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "home" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "info_links" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "info_strengths" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "info" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "dev_past_projects" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "dev" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "art_gallery" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "art" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "footer_links" ENABLE ROW LEVEL SECURITY;
  ALTER TABLE "footer" ENABLE ROW LEVEL SECURITY;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "users_sessions" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "users" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "media" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "posts" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "_posts_v" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "redirects" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "redirects_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "payload_kv" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "payload_locked_documents" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "payload_locked_documents_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "payload_preferences" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "payload_preferences_rels" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "payload_migrations" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "home" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "info_links" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "info_strengths" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "info" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "dev_past_projects" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "dev" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "art_gallery" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "art" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "footer_links" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "footer" DISABLE ROW LEVEL SECURITY;`)
}
